name: Update

on:
  schedule:
    # end of every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Update Database
      run: python update.py
    - name: Benchmark test
      run: python benchmark.py
    - name: Commit
      shell: bash
      run: |
        git config --global user.email "noreply@github.com"
        git config --global user.name "Updater Bot"
        git add iptocc/
        git commit -m "Auto Update Database" || true
        git push